services:
  db_postgres_my_profile:
    image: postgres:14
    container_name: db_postgres_my_profile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_my_profile:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  node_app_my_profile:
    container_name: my_profile
    build: .
    ports:
      - 80:5000
    depends_on:
      - db_postgres_my_profile
    env_file:
      - .env

volumes:
  pg_my_profile: